server:
  port: 8080
spring:
  application:
    name: security-demo
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/security?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update